"""
All members of class DataBindings are accessible from ID code files (in Python code) via various namespaces, including dat and datEmpty.
They provide access to linked values within all the known target tables. Follow dat or datEmpty with the target table name. For example:

    dat.samples.sampleID
    dat.addresses.get_first_linked_value("addressID")
"""

from typing import Optional, List, Union, Dict, Any
import traceback

from odm_map.id_generator.id_na import isna
from odm_map.id_generator.generator_config_keys import ConfigKeys

# Value to use if a value from one of the classes/tables is empty.
EMPTY_VALUE = "empty"


class DataBindings:
    """All data bindings accessible from ID generation code through the dat object (eg. dat.samples.sampleID)."""

    def __init__(
        self,
        generator,
        root_class: Optional[str],
        sub_class_names: Optional[List[str]],
        replace_empty_values: bool = True,
    ):
        """Constructor for DataBindings.

        Args:
            generator (IDGenerator): The ID Generator that the bindings are for.
            root_class (Optional[str]): The name of the class that this binding is for. A class name is a table name.
                If this is set then this binding represents a single table, and we retrieve an attribute on the
                binding to get values within a column of the table. If root_class is None then it is the top-level
                binding that contains all the classes (ie. tables). In this case, sub_class_names must be set to
                a list of all the recognized tables, and to retrieve any of these tables we retrieve an attribute
                on the binding to get the binding for the table (which we can in turn retrieve columns from). For
                example, bindingsObj.table. Since a new binding is returned when accessing this attribute, we can
                use the returned binding to then retrieve columns of the class, eg. bindingsObj.table.column. The
                actual row that is retrieved depends on the current_row_index of the generator.
            sub_class_names (Optional[List[str]]): If root_class is None, then sub_class_names must be set to a list
                of all the recognized classes (ie. tables). To retrieve the bindings for one of these classes, we
                would retrieve the attribute (using the name of the class) on this binding. For example,
                bindingsObj.column. The actual row that is retrieved depends on the current_row_index of the generator.
            replace_empty_values (bool, Optional): If True, then replace any empty values returned by this binding
                with the value EMPTY_VALUE.
        """
        self.generator = generator
        self.root_class = root_class
        self.replace_empty_values = replace_empty_values
        if sub_class_names:
            self.sub_classes = {
                class_name: DataBindings(
                    generator,
                    root_class=class_name,
                    sub_class_names=[],
                    replace_empty_values=self.replace_empty_values,
                )
                for class_name in sub_class_names
            }
        else:
            self.sub_classes = None

    def __str__(self) -> str:
        if self.sub_classes is None:
            sub_classes = None
        else:
            sub_classes = list(self.sub_classes.keys())
        return f"DataBindings(root_class={self.root_class}, sub_classes={sub_classes})"

    def __getattr__(self, name) -> Any:
        if self.sub_classes:
            return self.sub_classes[name]

        try:
            v = self.get_first_linked_value(name)
        except Exception as e:
            print(traceback.format_exc())
            raise e

        return v

    def get(self, name) -> Any:
        return self.__getattr__(name)

    def get_first_linked_value(
        self, target_slot: str, linkage_path: Union[str, Dict, List[Dict]] = None
    ) -> Any:
        # source_class and source_index are the current class and row being generated by the generator.
        # self.root_class and target_slot are the class and slot that we want to get the value of. The row
        # we retrieve the value from depends on which rows in self.root_class are linked to the row
        # in source_class at index source_index.
        source_class = self.generator.current_class
        source_index = self.generator.current_row_index

        if isinstance(linkage_path, str):
            named_class_linkages = self.generator.config.get(
                ConfigKeys.NAMED_CLASS_LINKAGES
            )
            if named_class_linkages is None:
                raise ValueError(
                    f"Named linkage path '{linkage_path}' specified for get_first_linked_value, but no named linkage paths specified in config file"
                )
            named_class_linkage = named_class_linkages.get(linkage_path)
            if named_class_linkage is None:
                raise ValueError(
                    f"Named linkage path '{linkage_path}' does not exist in config file"
                )
            new_linkage_path = named_class_linkage.get(source_class, {}).get(
                self.root_class, {}
            )
            if not new_linkage_path:
                raise ValueError(
                    f"Named linkage path '{new_linkage_path}' exists but no path from soure class '{source_class}' to target class '{self.root_class}' in config file"
                )
            linkage_path = new_linkage_path

        v = self.generator.get_first_linked_value(
            source_class,
            source_index,
            self.root_class,
            target_slot,
            linkage_path=linkage_path,
        )

        # Convert float to integer if it has no decimals
        if isinstance(v, float) and not isna(v):
            if int(v) == v:
                v = int(v)

        # Replace empty values
        if self.replace_empty_values:
            if isna(v) or v == "":
                v = EMPTY_VALUE
        else:
            if isna(v):
                v = ""

        return v
